version: "3.9"
services:
  aggregatorOrg1:
    container_name: core-aggregator.org1.example.com
    image: dist-fed-core-fl:latest
    labels:
      service: aggregator-core
    command:
      - "aggregator"
      - "localhost"
      - "8091"
    network_mode: "host"
  aggregatorOrg2:
    container_name: core-aggregator.org2.example.com
    image: dist-fed-core-fl:latest
    labels:
      service: aggregator-core
    command:
        - "aggregator"
        - "localhost"
        - "8092"
    network_mode: "host"
  leadAggregator:
    container_name: core-leadAggregator.org2.example.com
    image: dist-fed-core-fl:latest
    labels:
      service: leadAggregator-core
    command:
      - "leadAggregator"
      - "localhost"
      - "8082"
    network_mode: "host"
  trainer01:
    container_name: core-trainer01.example.com
    image: dist-fed-core-fl:latest
    labels:
      service: trainer-core
    command:
      - "trainer"
      - "localhost"
      - "8080"
      - "0"
    network_mode: "host"
  trainer02:
    container_name: core-trainer02.example.com
    image: dist-fed-core-fl:latest
    labels:
      service: trainer-core
    command:
      - "trainer"
      - "localhost"
      - "8081"
      - "1"
    network_mode: "host"
  flAdmin:
    container_name: core-flAdmin.org2.example.com
    image: dist-fed-core-fl:latest
    labels:
      service: flAdmin-core
    command:
      - "flAdmin"
      - "localhost"
      - "8083"
    depends_on:
      - trainer01
      - trainer02
      - aggregatorOrg1
      - aggregatorOrg2
      - leadAggregator
    network_mode: "host"