version: "3.9"
services:
  aggregator-org1:
    container_name: fed-aggregator.org1.example.com
    image: dist-fed-core:latest
    labels:
      service: aggregator-dist-fed-core
    command:
      - "localhost"
      - "8091"
  aggregator-org2:
    container_name: aggregator.org2.example.com
    image: dist-fed-gateway:latest
    labels:
      service: aggregator-dist-fed-gateway
    volumes:
      - ${DIST_FED_GATEWAY_CREDENTIAL_HOME}:/credential
    command:
      - "--fl.role=aggregator"
      - "--others.cert.path=/credential/org2.example.com/users/Aggregator1@org2.example.com/msp/signcerts/cert.pem"
      - "--others.key-dir.path=/credential/org2.example.com/users/Aggregator1@org2.example.com/msp/keystore"
      - "--others.tls-cert.path=/credential/org2.example.com/peers/peer0.org2.example.com/tls/ca.crt"
      - "--server.port=8092"
    ports:
      - "8092:8092"
  flAdmin:
    container_name: admin.org2.example.com
    image: dist-fed-gateway:latest
    labels:
      service: admin-dist-fed-gateway
    volumes:
      - ${DIST_FED_GATEWAY_CREDENTIAL_HOME}:/credential
    command:
      - "--fl.role=flAdmin"
      - "--others.cert.path=/credential/org2.example.com/users/Admin@org2.example.com/msp/signcerts/cert.pem"
      - "--others.key-dir.path=/credential/org2.example.com/users/Admin@org2.example.com/msp/keystore"
      - "--others.tls-cert.path=/credential/org2.example.com/peers/peer0.org2.example.com/tls/ca.crt"
      - "--server.port=8083"
    ports:
      - "8083:8083"
  leadAggregator:
    container_name: leadAggregator.org2.example.com
    image: dist-fed-gateway:latest
    labels:
      service: leadAggregator-dist-fed-gateway
    volumes:
      - ${DIST_FED_GATEWAY_CREDENTIAL_HOME}:/credential
    command:
      - "--fl.role=leadAggregator"
      - "--others.cert.path=/credential/org2.example.com/users/LeadAggregator1@org2.example.com/msp/signcerts/cert.pem"
      - "--others.key-dir.path=/credential/org2.example.com/users/LeadAggregator1@org2.example.com/msp/keystore"
      - "--others.tls-cert.path=/credential/org2.example.com/peers/peer0.org2.example.com/tls/ca.crt"
      - "--server.port=8082"
    ports:
      - "8082:8082"
  trainer01:
    container_name: trainer01.example.com
    image: dist-fed-gateway:latest
    labels:
      service: trainer-dist-fed-gateway
    volumes:
      # /home/hamid/Documents/fabric-samples/test-network/organizations/peerOrganizations
      - ${DIST_FED_GATEWAY_CREDENTIAL_HOME}:/credential
    command:
      - "--fl.role=trainer"
      - "--trainer.org1.cert.path=/credential/org1.example.com/users/Trainer1@org1.example.com/msp/signcerts/cert.pem"
      - "--trainer.org1.key-dir.path=/credential/org1.example.com/users/Trainer1@org1.example.com/msp/keystore"
      - "--trainer.org1.tls-cert.path=/credential/org1.example.com/peers/peer0.org1.example.com/tls/ca.crt"
      - "--trainer.org2.cert.path=/credential/org2.example.com/users/Trainer1@org2.example.com/msp/signcerts/cert.pem"
      - "--trainer.org2.key-dir.path=/credential/org2.example.com/users/Trainer1@org2.example.com/msp/keystore"
      - "--trainer.org2.tls-cert.path=/credential/org2.example.com/peers/peer0.org2.example.com/tls/ca.crt"
      - "--server.port=8080"
    ports:
      - "8080:8080"
  trainer02:
    container_name: trainer02.example.com
    image: dist-fed-gateway:latest
    labels:
      service: trainer-dist-fed-gateway
    volumes:
      - ${DIST_FED_GATEWAY_CREDENTIAL_HOME}:/credential
    command:
      - "--fl.role=trainer"
      - "--trainer.org1.cert.path=/credential/org1.example.com/users/Trainer2@org1.example.com/msp/signcerts/cert.pem"
      - "--trainer.org1.key-dir.path=/credential/org1.example.com/users/Trainer2@org1.example.com/msp/keystore"
      - "--trainer.org1.tls-cert.path=/credential/org1.example.com/peers/peer0.org1.example.com/tls/ca.crt"
      - "--trainer.org2.cert.path=/credential/org2.example.com/users/Trainer2@org2.example.com/msp/signcerts/cert.pem"
      - "--trainer.org2.key-dir.path=/credential/org2.example.com/users/Trainer2@org2.example.com/msp/keystore"
      - "--trainer.org2.tls-cert.path=/credential/org2.example.com/peers/peer0.org2.example.com/tls/ca.crt"
      - "--server.port=8081"
    ports:
      - "8081:8081"
