version: "3.9"
services:
  client:
    container_name: identity-client
    image: hmaid/hyperledger:dist-fed-core-identity-client
    labels:
      service: identity-client
    network_mode: "host"
    tty: true
    stdin_open: true
    command:
      - "--wallet-type"
      - "indy"
      - "--no-auto"
      - "--fabric-ca-client-enrollment-id"
      - "trainer1"
      - "--fabric-ca-client-enrollment-secret"
      - "trainer1pw"
      - "--fabric-ca-client-home"
      - "/home/hamid/Documents/fabric-samples/test-network/organizations/peerOrganizations/org1.example.com"
      - "--fabric-ca-client-ca-address"
      - "localhost"
      - "--fabric-ca-client-ca-port"
      - "7054"
      - "--fabric-ca-client-ca-name"
      - "ca-org1"
      - "--fabric-ca-client-tls-certfiles"
      - "/home/hamid/Documents/fabric-samples/test-network/organizations/fabric-ca/org1/ca-cert.pem"
      - "--fabric-ca-client-msp"
      - "/home/hamid/Documents/fabric-samples/test-network/organizations/peerOrganizations/org1.example.com/users/Trainer1@org1.example.com/msp"
  verifier:
    container_name: identity-verifier
    image: hmaid/hyperledger:dist-fed-core-identity-verifier
    labels:
      service: identity-verifier
    network_mode: "host"
    tty: true
    stdin_open: true
    command:
      - "--wallet-type"
      - "indy"
      - "--no-auto"
      - "--fabric-ca-client-enrollment-id"
      - "trainer1"
      - "--fabric-ca-client-enrollment-secret"
      - "trainer1pw"
      - "--fabric-ca-client-home"
      - "/home/hamid/Documents/fabric-samples/test-network/organizations/peerOrganizations/org1.example.com"
      - "--fabric-ca-client-ca-address"
      - "localhost"
      - "--fabric-ca-client-ca-port"
      - "7054"
      - "--fabric-ca-client-ca-name"
      - "ca-org1"
      - "--fabric-ca-client-tls-certfiles"
      - "/home/hamid/Documents/fabric-samples/test-network/organizations/fabric-ca/org1/ca-cert.pem"
      - "--fabric-ca-client-msp"
      - "/home/hamid/Documents/fabric-samples/test-network/organizations/peerOrganizations/org1.example.com/users/Trainer1@org1.example.com/msp"
  issuer:
    container_name: identity-issuer
    image: hmaid/hyperledger:dist-fed-core-identity-issuer
    labels:
      service: identity-issuer
    network_mode: "host"
    tty: true
    stdin_open: true
    command:
      - "--wallet-type"
      - "indy"
      - "--no-auto"